// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4QNZB5J7YcHuPuCj97-HC8x1qVM55rTg',
    appId: '1:139192087809:web:d017324f3cac16a2701700',
    messagingSenderId: '139192087809',
    projectId: 'umous-e35d7',
    authDomain: 'umous-e35d7.firebaseapp.com',
    storageBucket: 'umous-e35d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLe9HZ1dwwYeum6g4881NYSWZMmBYoPKQ',
    appId: '1:139192087809:android:9a56c4c3ad631628701700',
    messagingSenderId: '139192087809',
    projectId: 'umous-e35d7',
    storageBucket: 'umous-e35d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChdWctabxdvbjl4cC4aHC_raodfKeXrMA',
    appId: '1:139192087809:ios:bee195a538a06079701700',
    messagingSenderId: '139192087809',
    projectId: 'umous-e35d7',
    storageBucket: 'umous-e35d7.firebasestorage.app',
    iosBundleId: 'com.example.umous',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChdWctabxdvbjl4cC4aHC_raodfKeXrMA',
    appId: '1:139192087809:ios:bee195a538a06079701700',
    messagingSenderId: '139192087809',
    projectId: 'umous-e35d7',
    storageBucket: 'umous-e35d7.firebasestorage.app',
    iosBundleId: 'com.example.umous',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4QNZB5J7YcHuPuCj97-HC8x1qVM55rTg',
    appId: '1:139192087809:web:446ca8a58dc37cc4701700',
    messagingSenderId: '139192087809',
    projectId: 'umous-e35d7',
    authDomain: 'umous-e35d7.firebaseapp.com',
    storageBucket: 'umous-e35d7.firebasestorage.app',
  );
  static const FirebaseOptions linux = FirebaseOptions(
  apiKey: 'AIzaSyD4QNZB5J7YcHuPuCj97-HC8x1qVM55rTg',
  appId: '1:139192087809:web:446ca8a58dc37cc4701700',
  messagingSenderId: '139192087809',
  projectId: 'umous-e35d7',
  authDomain: 'umous-e35d7.firebaseapp.com',
  storageBucket: 'umous-e35d7.firebasestorage.app',
);

}
